### ISSUE TITLE
docker-compose up -d fails

### ISSUE THREAD

**Issue by ktiedt** [funkypenguin/docker-htpc-suite#1]
```
Building datastore
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

Just found your compose suite and was hoping to simplify my setup by containerizing things, however I am at a loss as to what this failure means.

Would you have any idea here? I am on the latest versions:

```
Docker version 1.9.1, build a34a1d5
docker-compose version 1.5.2, build 7240ff3
```

Any nudges in the right direction would be helpful, thanks!

**Comment by funkypenguin** [comment]
Hi,

Sorry, I missed this over an extended Christmas holiday! I agree this seems unusual, have you had any success progressing it?

D

**Comment by ktiedt** [comment]
I have not, tried various things for a day or two and have up. Hoping to
hear someone else had seen and solved it.

**Comment by funkypenguin** [comment]
OK, try creating "Dockerfile" in the same directory with the following contents:

```
FROM phusion/baseimage:0.9.15
MAINTAINER funkypenguin <davidy@funkypenguin.co.nz>
#Based on the work of needo <needo@superhero.org>
#Based on the work of Eric Schultz <eric@startuperic.com>
#Thanks to Tim Haak <tim@haak.co.uk>
ENV DEBIAN_FRONTEND noninteractive

# Set correct environment variables
ENV HOME /root

# Use baseimage-docker's init system
CMD ["/sbin/my_init"]

# chfn workaround - Known issue within Dockers
RUN ln -s -f /bin/true /usr/bin/chfn

# This is a datastore
# So do nothing
```

The original version of my docker-compose.yml file relied on a Dockerfile in the same directory to create the data volume - next version will be a bit more polished!

**Comment by ktiedt** [comment]
This does appear to fix the problem, except it would seem the port listings in the yaml file are backwards?
